### ISSUE TITLE
[Home] Some UI is not match with design

### ISSUE THREAD

**Issue by haimtp** [DungBuiTien1999/zero-to-one#1]
**1. Khoảng cách giữa header và slide show quá bự:**

- Actual: có khoảng trống giữa thanh header và slideshow bên dưới
![image](https://user-images.githubusercontent.com/89384577/147378893-ba9efd91-6d04-4f80-845b-71176a9ade50.png)

- Expect: Không có khoảng trỗng này
![image](https://user-images.githubusercontent.com/89384577/147378902-c37b889b-0664-4106-8b8c-dbc35500b6b9.png)

**2. Nút "next/previous" không đúng màu, hơi bự, lệch vị trí**

- Actual: màu cam, nút ko nằm giữa
![image](https://user-images.githubusercontent.com/89384577/147378937-1832ab75-fc09-4aa3-9ab4-ce4043618a46.png)

- Expect: Màu vàng, nút nằm giữa so với cục course
![image](https://user-images.githubusercontent.com/89384577/147378951-1dda7d53-2da4-4d2b-93bc-0fe2a593bfb4.png)

3. Tiêu đề chưa giống như design

- Actual: Màu cam thường, style nhạt, nút "see all" không nằm thẳng hàng với title
![image](https://user-images.githubusercontent.com/89384577/147379015-e705192a-20d3-4148-a38a-d41149d30d66.png)

- Expect: Màu cam (linear), style đậm, nút "see all" nằm thẳng hàng với title
![image](https://user-images.githubusercontent.com/89384577/147379034-a94d32ac-2649-4e73-a8ee-2d1677cc5134.png)

4. Màu mục danh mục ko giống trong design

- Actual: Màu cam (linear)
![image](https://user-images.githubusercontent.com/89384577/147379050-d9e6308b-73e5-44ff-9381-84b8aa42e9e6.png)

- Expect: Màu vàng
![image](https://user-images.githubusercontent.com/89384577/147379059-c30fa4a5-a7f3-4354-82ca-2e7b0b42d35d.png)

**Comment by hoangtiendat** [comment]
### Đã sửa.
**1. Đã xóa khoảng cách giữa header và slide:**
![image](https://user-images.githubusercontent.com/42890655/147382037-df198c0d-2638-498f-ac1a-a3f42e5e5aee.png)
**2 &3. Nút "next/previous" đã chỉnh đúng màu, vị trí; Tiêu đề màu giống như design**
![image](https://user-images.githubusercontent.com/42890655/147382064-d9f48b9e-b46c-4e65-a4ab-63a4989b366c.png)
**4. Màu mục danh mục đã giống trong design:**
![image](https://user-images.githubusercontent.com/42890655/147382080-1babce0a-45fc-4cc7-a7e4-3d11aa7a2c53.png)
