### ISSUE TITLE
[Home Page] Chỉnh sửa giao diện hompage

### ISSUE THREAD

**Issue by haimtp** [DungBuiTien1999/zero-to-one#2]
**1. Nút xem tất cả ko consistent với nhau**
  - Actual: Ở row trên thì có màu nền, row dưới thì ko có 
  
![image](https://user-images.githubusercontent.com/89384577/148183048-3f55aa5d-0533-41ac-a150-7a23912786a5.png)
![image](https://user-images.githubusercontent.com/89384577/148183082-544b5283-86df-4621-b12c-28e151e47e5d.png)

- Expect: Đồng bộ nút xem tất cả lại như UI 
![image](https://user-images.githubusercontent.com/89384577/148183210-f7b05b99-b1de-43ca-a35a-2200f69ea6a1.png)
![image](https://user-images.githubusercontent.com/89384577/148183245-34033e60-2922-442d-8e6d-a7647342c408.png)

![image](https://user-images.githubusercontent.com/89384577/148183295-1517d879-fb3e-40ad-850c-dcea0446b242.png)

(*) Lưu ý:
+ Thêm nút xem tất cả cho phần danh mục
+ Export lại ảnh (x2) của phần bảng xếp hạng và tin tức vì có update UI

  
**2. Chiều rộng homepage bị tràn ra**

Actual: Có thanh scroll ngang 
![image](https://user-images.githubusercontent.com/89384577/148185558-9f73179d-557c-467f-9db4-b9ef5a44a2bc.png)

Expect: Không có thanh scroll ngang, width fit đc với các màn hình 14' để có thể demo được

**Comment by hoangtiendat** [comment]
Đã sửa
